- name: Get Instance ID
  set_fact:
    apache_id: "{{ hostvars[groups['apache'][0]].instance_id }}"
    nginx_id: "{{ hostvars[groups['nginx'][0]].instance_id }}"
    haproxy_id: "{{ hostvars[groups['proxy'][0]].instance_id }}"

- name: Remove servers
  ec2:
    state: absent
    instance_ids: '{{ item }}'
    region: '{{ region }}'
  with_items:
    - "{{ apache_id }}"
    - "{{nginx_id}}"
    - "{{haproxy_id}}"

# This is done automatically
- name: remove servers from inventory
  lineinfile:
    dest: "{{ lookup('env','ANSIBLEENV') }}/hosts"
    state: absent
    regexp: "^{{item}}"
  with_items:
    - "{{ groups['apache'] }}"
    - "{{ groups['nginx'] }}"
    - "{{ groups['proxy'] }}"
