# Build the entire monitoring solution
- hosts: ec2
  connection: local
  gather_facts: false
  roles:
    - ec2

- hosts: elk
  become: True
  gather_facts: True
  roles:
    - elasticsearch
    - kibana

- hosts: apache
  become: True
  gather_facts: True
  roles:
    - httpd
    - posthttpd
    - java
    - logstash

- hosts: nginx
  become: True
  gather_facts: True
  roles:
    - prenginx
    - nginx
    - java
    - logstash

- hosts: proxy
  become: True
  gather_facts: True
  roles:
    - haproxy
    - java
    - logstash
