# Build the entire monitoring solution
- hosts: ec2
  connection: local
  gather_facts: false
  roles:
    - ec2

- hosts: elk
  become: True
  gather_facts: True
  roles:
    - common
    - elasticsearch
    - kibana

- hosts: apache
  become: True
  gather_facts: True
  roles:
    - common
    - apachehttpd
    - java
    - ansible-role-logstash

- hosts: nginx
  become: True
  gather_facts: True
  roles:
    - common
    - prenginx
    - nginx
    - java
    - ansible-role-logstash

- hosts: proxy
  become: True
  gather_facts: True
  roles:
    - common
    - haproxy
    - java
    - ansible-role-logstash
