- name: Display attributes
  debug:
    msg:
      - "SSH Key: {{ ansible_ssh_private_key_file }}"
      - "User: {{ ansible_ssh_user }}"
      - "SSH Args: {{ ansible_ssh_common_args }}"

- name: Create ec2 for Apache
  ec2:
    key_name: "{{ sshkey }}"
    group: "{{ secgrps['web'] }}"
    instance_type: "{{logstash_type}}"
    image: "{{ ami[region] }}"
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnets['private'] }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ project_name }}.Apache"
      Environment: "{{ env }}"
  when: groups['apache'] | length == 0
  register: ec2Apache

- name: Wait for SSH to come up
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 30
    timeout: 320
  when: groups['apache'] | length == 0
  with_items: "{{ ec2Apache.instances }}"

- name: Add to inventory
  lineinfile:
    dest: "{{ lookup('env','ANSIBLEENV') }}/hosts"
    insertafter: '^\[apache\]'
    line: "{{ item.public_dns_name }} instance_id={{ item.id}} private_ip={{ item.private_ip }}"
  when: groups['apache'] | length == 0
  with_items: "{{ ec2Apache.instances }}"

- name: Refresh inventory
  meta: refresh_inventory
